name: VoxelViewer
main: com.thevoxelbox.viewer.VoxelViewer
version: 0.1
commands:
  vvcache:
    description: Rebuild VoxelViewer cache completely. Requires OP status.
    usage: /vvcache
  vvlen:
    description: Get the number of chunks currently in the queue. Requires OP status.
    usage: /vvlen
  genregion:
    description: Generate a region of 1024 chunks. Requires OP status.
    usage: /genregion x z [world]